//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDDN_V2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AspNetUser
    {
        public string Id { get; set; }
        [EmailAddress]
        public string Email { get; set; }

        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        [Phone]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Mobile Number should be of 10 digits only")]
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Guardian_Name { get; set; }
        [RegularExpression(@"^([0-9]{6})$", ErrorMessage = "Invalid Pincode ")]
        public string Pincode { get; set; }
        [Phone]
        public string Mobile_Number { get; set; }
        [DataType(DataType.Date)]

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public string Date_of_Birth { get; set; }
        [MaxLength(100)]
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }

        public string Country { get; set; }
        public int AccountNumber { get; set; }
        public string AccountType { get; set; }
        public int Balance { get; set; }
    }
}
