//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDDN_V2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Transaction
    {
        public int Id { get; set; }
        public string UserId { get; set; }
       
        public int FromAccount { get; set; }
        [Display(Name ="AccountNumber")]
        [Required]
        [RegularExpression(@"^([0-9]{9})$", ErrorMessage = "Invalid AccountNumber ")]
        public int ToAccount { get; set; }
        [Required]
        [Display(Name = "Confirm AccountNumber")]
        public int ConfirmToAccount { get; set; }
        [Display(Name ="Amount(In Rupees)")]
        
        [Required]
        public int Amount { get; set; }
        [Required]
        public System.DateTime Date { get; set; }
        [Display(Name ="Recipient's Name")]
        public string Recipient { get; set; }
        
    }
}
